### PR TITLE
ADD rules to enforce strict comparaison

### PR DESCRIPTION
**Pull request by DaveLiddament**
Don't allow usage of: 

- `==`
- `!=`

### CODE REVIEW

**Comment by szepeviktor** [comment]
This is implemented in https://github.com/phpstan/phpstan-strict-rules/blob/1.6.x/src/Rules/DisallowedConstructs/DisallowedLooseComparisonRule.php

**Comment by DaveLiddament** [comment]
[Update PHPStan settings to prevent usage of `!=` and `==`](https://trello.com/c/1cRKZdZS/84-update-phpstan-settings-to-prevent-usage-of-and)

**Comment by DaveLiddament** [comment]
Thanks. I though it was, but we already use strict rules and this problem didn't get picked up. I must  have mis-configured the plugin. I'll go check.

**Comment by DaveLiddament** [comment]
Fixed by config change: https://github.com/TommyTrinder/framepoint/pull/853

**Comment by DaveLiddament** [comment]
@szepeviktor thanks for your input on this. It turns out that by default the `disallowedLooseComparison` requires `bleeding-edge` to be enable.  

To enable in `phpstan.neon` without running bleeding edge add:

```neon
parameters:
    strictRules:
      disallowedLooseComparison: true
```

**Pull request closed without merging**
